# Generated by Django 4.2.15 on 2024-09-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_remove_profile_id_user_profile_role_and_more'),
        ('core', '0002_profile_role_vet_pet'),
    ]

    operations = [
    ]
