# Generated by Django 4.2.15 on 2024-08-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_role_vet_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=20),
        ),
    ]
