# Generated by Django 4.2.15 on 2024-09-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pet_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
